// <auto-generated />
using System;
using HyperV.CentralManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HyperV.CentralManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260222204638_AddContentLibrary")]
    partial class AddContentLibrary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HyperV.CentralManagement.Models.AgentHost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ClusterName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HostType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HyperVVersion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HypervisorVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("AgentHosts");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.AlertDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentHostId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EvaluationPeriods")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<double>("ThresholdValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("AlertDefinitions");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.AlertInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("AcknowledgedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AgentHostId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentHostName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("AlertDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<double>("CurrentValue")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("FiredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ResolvedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VmInventoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("VmName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AlertDefinitionId");

                    b.HasIndex("Status");

                    b.ToTable("AlertInstances");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.AlertNotificationChannel", b =>
                {
                    b.Property<Guid>("AlertDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotificationChannelId")
                        .HasColumnType("uuid");

                    b.HasKey("AlertDefinitionId", "NotificationChannelId");

                    b.HasIndex("NotificationChannelId");

                    b.ToTable("AlertNotificationChannels");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.Cluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.ClusterNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentHostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentHostId");

                    b.HasIndex("ClusterId");

                    b.ToTable("ClusterNodes");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.ContentLibraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.ToTable("ContentLibraryItems");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.ContentLibrarySubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentHostId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastSyncUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LibraryItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("SyncError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LibraryItemId");

                    b.HasIndex("AgentHostId", "LibraryItemId")
                        .IsUnique();

                    b.ToTable("ContentLibrarySubscriptions");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.DrsConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AutomationLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<int>("CpuImbalanceThreshold")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EvaluationIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MemoryImbalanceThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("MinBenefitPercent")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("DrsConfigurations");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.DrsRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppliedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("AppliedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationAgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("DrsConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<double>("EstimatedBenefitPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SourceAgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceAgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VmInventoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("VmName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("DrsRecommendations");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.HaConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AdmissionControl")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailureThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("HeartbeatIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("ReservedCpuPercent")
                        .HasColumnType("integer");

                    b.Property<int>("ReservedMemoryPercent")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("HaConfigurations");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.HaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentHostId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentHostName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VmInventoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("VmName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("HaEvents");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.HaVmOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HaConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<int>("RestartOrder")
                        .HasColumnType("integer");

                    b.Property<int>("RestartPriority")
                        .HasColumnType("integer");

                    b.Property<Guid>("VmInventoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HaConfigurationId", "VmInventoryId")
                        .IsUnique();

                    b.ToTable("HaVmOverrides");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.MetricDataPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AgentHostId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("VmInventoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("AgentHostId", "MetricName", "TimestampUtc");

                    b.ToTable("MetricDataPoints");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.MigrationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationAgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IncludeStorage")
                        .HasColumnType("boolean");

                    b.Property<string>("InitiatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("LiveMigration")
                        .HasColumnType("boolean");

                    b.Property<string>("PreCheckResults")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceAgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceAgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VmInventoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("VmName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("MigrationTasks");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.NotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("NotificationChannels");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Resource", "Action")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.RegistrationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UsedByAgentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RegistrationTokens");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentHostId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.VmFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("VmFolders");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.VmInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentHostId")
                        .HasColumnType("uuid");

                    b.Property<int>("CpuCount")
                        .HasColumnType("integer");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastSyncUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemoryMB")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("VmId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("AgentHostId", "VmId")
                        .IsUnique();

                    b.ToTable("VmInventory");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.AlertInstance", b =>
                {
                    b.HasOne("HyperV.CentralManagement.Models.AlertDefinition", "AlertDefinition")
                        .WithMany("Instances")
                        .HasForeignKey("AlertDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertDefinition");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.AlertNotificationChannel", b =>
                {
                    b.HasOne("HyperV.CentralManagement.Models.AlertDefinition", "AlertDefinition")
                        .WithMany("NotificationChannels")
                        .HasForeignKey("AlertDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyperV.CentralManagement.Models.NotificationChannel", "NotificationChannel")
                        .WithMany("AlertDefinitions")
                        .HasForeignKey("NotificationChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertDefinition");

                    b.Navigation("NotificationChannel");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.ClusterNode", b =>
                {
                    b.HasOne("HyperV.CentralManagement.Models.AgentHost", "AgentHost")
                        .WithMany()
                        .HasForeignKey("AgentHostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyperV.CentralManagement.Models.Cluster", "Cluster")
                        .WithMany("Nodes")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentHost");

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.ContentLibraryItem", b =>
                {
                    b.HasOne("HyperV.CentralManagement.Models.UserAccount", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.ContentLibrarySubscription", b =>
                {
                    b.HasOne("HyperV.CentralManagement.Models.AgentHost", "AgentHost")
                        .WithMany()
                        .HasForeignKey("AgentHostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyperV.CentralManagement.Models.ContentLibraryItem", "LibraryItem")
                        .WithMany("Subscriptions")
                        .HasForeignKey("LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentHost");

                    b.Navigation("LibraryItem");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.DrsConfiguration", b =>
                {
                    b.HasOne("HyperV.CentralManagement.Models.Cluster", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.HaConfiguration", b =>
                {
                    b.HasOne("HyperV.CentralManagement.Models.Cluster", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.HaVmOverride", b =>
                {
                    b.HasOne("HyperV.CentralManagement.Models.HaConfiguration", "HaConfiguration")
                        .WithMany("VmOverrides")
                        .HasForeignKey("HaConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HaConfiguration");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.RolePermission", b =>
                {
                    b.HasOne("HyperV.CentralManagement.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyperV.CentralManagement.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.UserRole", b =>
                {
                    b.HasOne("HyperV.CentralManagement.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyperV.CentralManagement.Models.UserAccount", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.VmFolder", b =>
                {
                    b.HasOne("HyperV.CentralManagement.Models.VmFolder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.VmInventory", b =>
                {
                    b.HasOne("HyperV.CentralManagement.Models.AgentHost", "AgentHost")
                        .WithMany()
                        .HasForeignKey("AgentHostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyperV.CentralManagement.Models.VmFolder", "Folder")
                        .WithMany("Vms")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AgentHost");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.AlertDefinition", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("NotificationChannels");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.Cluster", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.ContentLibraryItem", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.HaConfiguration", b =>
                {
                    b.Navigation("VmOverrides");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.NotificationChannel", b =>
                {
                    b.Navigation("AlertDefinitions");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.UserAccount", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HyperV.CentralManagement.Models.VmFolder", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Vms");
                });
#pragma warning restore 612, 618
        }
    }
}
